### PR TITLE
webproxy: T2581: implement proxy chaining

### PR DESCRIPTION
**Pull request by githonk**
add configuration option to allow for proxy chaining (squid option "cache_peer")

### CODE REVIEW

**Review by dmbaturin — COMMENTED** [review]
We've had a policy against new features in Perl and old node.def's since 1.2.0.

However, since this change is relatively small and web proxy still isn't rewritten to the new style, I'm inclined to break my own rules.

Let's  see what other maintainers think.

**Comment by githonk** [comment]
> We've had a policy against new features in Perl and old node.def's since 1.2.0.
> 
> However, since this change is relatively small and web proxy still isn't rewritten to the new style, I'm inclined to break my own rules.

Yes, I was thinking of rewriting all in the new style, but it seemed excessive for the small change.

**Comment by c-po** [comment]
@githonk thanks for the contribution. As outlines by @dmbaturin we usually do not accept extensions to legacy code. But as webproxy still has an unforseen future (some want to drop it, some want to keep it, and some are in the middle) we can accept this contribution.

As large enterprises still use proxies (mainly for authentication purporses only and not caching I now also feel for keeping it).

According to our guidelines a Phabricator task should be created and the commit message should be properly formatted: https://docs.vyos.io/en/latest/contributing/development.html#prepare-patch-commit

Can you please correct this? Then there is no reason to not include it.

**Comment by githonk** [comment]
> Can you please correct this? Then there is no reason to not include it.
@c-po sure, will do.

We appreciate that webproxy is planned to being kept, we heavily rely on it in our infrastructure (as you said: large enterprises). We don't need caching, but URL filtering and authentication.

**Comment by c-po** [comment]
@githonk can you please also reword your git commits to reflect the task ID?

**Comment by githonk** [comment]
> @githonk can you please also reword your git commits to reflect the task ID?

Done.

**Pull request merged**
