### PR TITLE
Fixes T1060: Add command webproxy proxy-bypass-source to bypass proxy…

### PR DESCRIPTION
**Pull request by dsteinkopf**
Add command `webproxy proxy-bypass-source` to bypass proxy based on source IP address.

This is useful for disabling the (e.g. transparent) proxy only for specific devices. (I am using it to make Netflix work again by disabling the IP address of my Fire TV where Netflix runs on.)

(If you are able to read German, I wrote a : [blog post](https://nerdblog.steinkopf.net/2016/09/vyos-webproxy-bypass-basierend-auf-quell-ip/) about this. Now I would like to integrate this into vyos.)

### CODE REVIEW

**Comment by dmbaturin** [comment]
I have reservations about using inline iptables commands like that, especially in the light of the future firewall rewrite to use iptables-save/iptables-restore functionality.

**Comment by c-po** [comment]
> I have reservations about using inline iptables commands like that, especially in the light of the future firewall rewrite to use iptables-save/iptables-restore functionality.

I can second this but do we currently have a "better" approach?  At this time there is also https://github.com/vyos/vyatta-webproxy/blob/current/scripts/vyatta-update-webproxy.pl which is invoked from `service webproxy`

**Comment by dsteinkopf** [comment]
Just to understand (I am very new here):
* This problem is nothing newly introduced by this change (webproxy proxy-bypass was the same).
* What do you mean by "inline iptables commands"? Invoking iptables by such a "subcommand"? What would be a better way?

**Comment by c-po** [comment]
What @dmbaturin means by `inline iptables commands` is that iptables is called directly from the `node.def` file.

Also @dsteinkopf is right - this behavior is legacy code (just moved around a node and added asecond one). IMHO this is ok - as to my knowledge there is no better way to do it right now.

**Comment by dmbaturin** [comment]
@dsteinkopf See T1090 for related considerations.

**Comment by dsteinkopf** [comment]
for convenience: https://phabricator.vyos.net/T1090

**Pull request merged**
